from utils.kelly_criterion.bkc import basic_kelly
from utils.kelly_criterion.ikc import investment_kelly
from utils.kelly_criterion.mokc import multiple_outcomes_kelly
from utils.kelly_criterion.mckc import multiple_conditions_kelly